TRUNCATE patients CASCADE;

INSERT INTO patients (
  id,
  tenant_id,
  national_id,
  national_id_type,
  issuing_country,
  first_name,
  last_name,
  middle_name,
  date_of_birth,
  gender,
  marital_status,
  nationality,
  preferred_language,
  phone_number,
  email,
  address_line1,
  address_line2,
  city,
  postal_code,
  country,
  emergency_contact,
  insurance_info,
  created_by,
  created_at_facility,
  registration_source,
  registration_notes,
  status,
  created_at,
  updated_at,
  updated_by,
  updated_at_facility
) VALUES
  (
    uuid_from_text('patient-ahmed-al-mansoori'),
    uuid_from_text('tenant-demo-0001'),
    '784198012345671',
    'national_id',
    'AE',
    'Ahmed',
    'Al Mansoori',
    NULL,
    DATE '1985-03-15',
    'male',
    'married',
    'UAE',
    'ar',
    '+971501234567',
    'ahmed.mansoori@example.ae',
    'Sheikh Zayed Road',
    NULL,
    'Dubai',
    '00000',
    'AE',
    '{"name":"Fatima Al Mansoori","relation":"spouse","phone":"+971502345678"}'::jsonb,
    '{"payer":"Daman","memberId":"DAM123456"}'::jsonb,
    uuid_from_text('user-super-admin-uuid'),
    uuid_from_text('facility-demo-clinic-uuid'),
    'manual',
    'Initial registration via front desk',
    'active',
    NOW(),
    NOW(),
    NULL,
    NULL
  ),
  (
    uuid_from_text('patient-fatima-hassan'),
    uuid_from_text('tenant-demo-0001'),
    '784199007654321',
    'national_id',
    'AE',
    'Fatima',
    'Hassan',
    NULL,
    DATE '1990-07-22',
    'female',
    'single',
    'UAE',
    'en',
    '+971509876543',
    'fatima.hassan@example.ae',
    'Marina Walk',
    NULL,
    'Dubai',
    '00000',
    'AE',
    '{"name":"Sara Hassan","relation":"mother","phone":"+971503456789"}'::jsonb,
    '{"payer":"NeuroHealth","memberId":"NH987654"}'::jsonb,
    uuid_from_text('user-super-admin-uuid'),
    uuid_from_text('facility-demo-clinic-uuid'),
    'portal',
    'Self-registered via patient portal',
    'active',
    NOW(),
    NOW(),
    NULL,
    NULL
  ),
  (
    uuid_from_text('patient-john-smith'),
    uuid_from_text('tenant-demo-0001'),
    'A12345678',
    'passport',
    'GB',
    'John',
    'Smith',
    NULL,
    DATE '1978-11-08',
    'male',
    'married',
    'UK',
    'en',
    '+971555555555',
    'john.smith@example.ae',
    'Corniche Road',
    NULL,
    'Abu Dhabi',
    '00000',
    'AE',
    '{"name":"Mary Smith","relation":"spouse","phone":"+971556666666"}'::jsonb,
    '{"payer":"AXA","memberId":"AXA556677"}'::jsonb,
    uuid_from_text('user-demo-admin-uuid'),
    uuid_from_text('facility-demo-hospital-uuid'),
    'import',
    'Migrated from legacy system',
    'active',
    NOW(),
    NOW(),
    NULL,
    NULL
  );

-- Verification query
SELECT id, first_name, last_name, national_id_type, national_id FROM patients ORDER BY created_at LIMIT 10;
