-- Administrative Services Seed Data
-- Non-clinical services including registration, consultation fees, room charges, etc.

TRUNCATE administrative_services CASCADE;

INSERT INTO administrative_services (
  id,
  tenant_id,
  service_name,
  service_code,
  billing_code,
  billing_code_type,
  billing_description,
  service_category,
  service_type,
  department,
  care_setting,
  description,
  duration_minutes,
  requires_staff,
  staff_type,
  requires_room,
  room_type,
  is_taxable,
  is_active,
  metadata,
  created_at,
  updated_at
) VALUES
  -- =========================================================================
  -- REGISTRATION SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'New Patient Registration',
    'REG-NEW',
    '99201',
    'CPT',
    'New patient registration and medical record creation',
    'registration',
    'new_patient',
    'general',
    'ANY',
    'Registration fee for first-time patients including medical record creation and patient ID issuance',
    15,
    true,
    'administrative',
    false,
    NULL,
    true,
    true,
    '{"priority": "high", "documentRequired": ["emirates_id", "insurance_card"]}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Follow-up Patient Registration',
    'REG-FOLLOWUP',
    '99211',
    'CPT',
    'Follow-up patient registration',
    'registration',
    'follow_up',
    'general',
    'ANY',
    'Registration fee for existing patients returning for follow-up visits',
    10,
    true,
    'administrative',
    false,
    NULL,
    true,
    true,
    '{"priority": "standard"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Emergency Registration',
    'REG-EMR',
    '99281',
    'CPT',
    'Emergency patient registration',
    'registration',
    'emergency',
    'emergency',
    'ANY',
    'Fast-track registration for emergency patients',
    5,
    true,
    'administrative',
    false,
    NULL,
    true,
    true,
    '{"priority": "urgent", "skipValidation": true}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- CONSULTATION SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'General Physician Consultation - New',
    'CONS-GP-NEW',
    '99203',
    'CPT',
    'New patient consultation with General Physician',
    'consultation',
    'new_patient',
    'OPD',
    'OP',
    'Comprehensive consultation for new patients with general physician including history taking, examination, and treatment plan',
    30,
    true,
    'physician',
    true,
    'consultation_room',
    true,
    true,
    '{"specialty": "general_medicine"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'General Physician Consultation - Follow-up',
    'CONS-GP-FOLLOWUP',
    '99213',
    'CPT',
    'Follow-up consultation with General Physician',
    'consultation',
    'follow_up',
    'OPD',
    'OP',
    'Follow-up consultation for existing patients to monitor progress and adjust treatment',
    20,
    true,
    'physician',
    true,
    'consultation_room',
    true,
    true,
    '{"specialty": "general_medicine"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Specialist Consultation - New',
    'CONS-SPEC-NEW',
    '99204',
    'CPT',
    'New patient consultation with Specialist',
    'consultation',
    'new_patient',
    'OPD',
    'OP',
    'Comprehensive consultation for new patients with medical specialist',
    45,
    true,
    'physician',
    true,
    'consultation_room',
    true,
    true,
    '{"specialty": "specialist"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Specialist Consultation - Follow-up',
    'CONS-SPEC-FOLLOWUP',
    '99214',
    'CPT',
    'Follow-up consultation with Specialist',
    'consultation',
    'follow_up',
    'OPD',
    'OP',
    'Follow-up consultation with specialist to review treatment progress',
    30,
    true,
    'physician',
    true,
    'consultation_room',
    true,
    true,
    '{"specialty": "specialist"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Emergency Physician Consultation',
    'CONS-EMR',
    '99285',
    'CPT',
    'Emergency physician consultation',
    'consultation',
    'emergency',
    'emergency',
    'OP',
    'Urgent consultation for emergency cases requiring immediate medical attention',
    20,
    true,
    'physician',
    true,
    'treatment_room',
    true,
    true,
    '{"specialty": "emergency_medicine", "priority": "urgent"}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- ADMISSION SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'General Ward Admission',
    'ADM-WARD',
    '99221',
    'CPT',
    'Initial hospital admission to general ward',
    'admission',
    'routine',
    'IPD',
    'IP',
    'Admission fee for general ward including initial assessment and bed allocation',
    30,
    true,
    'physician',
    false,
    NULL,
    true,
    true,
    '{"wardType": "general"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'ICU Admission',
    'ADM-ICU',
    '99223',
    'CPT',
    'Initial ICU admission',
    'admission',
    'emergency',
    'ICU',
    'IP',
    'Admission to intensive care unit for critical patients requiring continuous monitoring',
    45,
    true,
    'physician',
    false,
    NULL,
    true,
    true,
    '{"wardType": "icu", "priority": "critical"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Day Care Admission',
    'ADM-DAYCARE',
    '99234',
    'CPT',
    'Day care admission for minor procedures',
    'admission',
    'routine',
    'DAYCARE',
    'DAYCARE',
    'Short-stay admission for procedures requiring observation but not overnight stay',
    20,
    true,
    'nurse',
    false,
    NULL,
    true,
    true,
    '{"maxStayHours": 12}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- ROOM CHARGES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'General Ward Bed - Per Day',
    'ROOM-WARD-DAY',
    'ROOM-001',
    'LOCAL',
    'Daily charge for general ward bed',
    'room_charge',
    NULL,
    'IPD',
    'IP',
    'Daily room charge for general ward bed including basic amenities',
    NULL,
    false,
    NULL,
    false,
    NULL,
    true,
    true,
    '{"bedType": "general", "chargeFrequency": "daily"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Semi-Private Room - Per Day',
    'ROOM-SEMI-DAY',
    'ROOM-002',
    'LOCAL',
    'Daily charge for semi-private room',
    'room_charge',
    NULL,
    'IPD',
    'IP',
    'Daily room charge for semi-private room (2 beds) with attached bathroom',
    NULL,
    false,
    NULL,
    false,
    NULL,
    true,
    true,
    '{"bedType": "semi_private", "chargeFrequency": "daily", "bedsInRoom": 2}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Private Room - Per Day',
    'ROOM-PRIVATE-DAY',
    'ROOM-003',
    'LOCAL',
    'Daily charge for private room',
    'room_charge',
    NULL,
    'IPD',
    'IP',
    'Daily room charge for private room with attached bathroom and basic amenities',
    NULL,
    false,
    NULL,
    false,
    NULL,
    true,
    true,
    '{"bedType": "private", "chargeFrequency": "daily"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'ICU Bed - Per Day',
    'ROOM-ICU-DAY',
    'ROOM-ICU-001',
    'LOCAL',
    'Daily charge for ICU bed',
    'room_charge',
    NULL,
    'ICU',
    'IP',
    'Daily charge for ICU bed with continuous monitoring equipment',
    NULL,
    false,
    NULL,
    false,
    NULL,
    true,
    true,
    '{"bedType": "icu", "chargeFrequency": "daily", "includesMonitoring": true}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'VIP Suite - Per Day',
    'ROOM-VIP-DAY',
    'ROOM-004',
    'LOCAL',
    'Daily charge for VIP suite',
    'room_charge',
    NULL,
    'IPD',
    'IP',
    'Daily charge for VIP suite with premium amenities, living area, and attendant room',
    NULL,
    false,
    NULL,
    false,
    NULL,
    true,
    true,
    '{"bedType": "vip", "chargeFrequency": "daily", "amenities": ["tv", "wifi", "refrigerator", "attendant_room"]}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- NURSING SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'IV Cannulation',
    'NURS-IV-CANN',
    '36000',
    'CPT',
    'Intravenous cannulation and line insertion',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Insertion of IV cannula for medication or fluid administration',
    15,
    true,
    'nurse',
    false,
    NULL,
    true,
    true,
    '{"procedureType": "iv_access"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'IV Medication Administration',
    'NURS-IV-MED',
    '96374',
    'CPT',
    'Intravenous medication administration',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Administration of IV medication per dose',
    10,
    true,
    'nurse',
    false,
    NULL,
    true,
    true,
    '{"procedureType": "medication_admin"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Wound Dressing - Simple',
    'NURS-DRESS-SIMPLE',
    '12001',
    'CPT',
    'Simple wound dressing change',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Dressing change for simple wounds without complications',
    20,
    true,
    'nurse',
    true,
    'treatment_room',
    true,
    true,
    '{"woundType": "simple"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Wound Dressing - Complex',
    'NURS-DRESS-COMPLEX',
    '12002',
    'CPT',
    'Complex wound dressing change',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Dressing change for complex wounds, burns, or surgical wounds',
    30,
    true,
    'nurse',
    true,
    'treatment_room',
    true,
    true,
    '{"woundType": "complex"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Catheterization - Urinary',
    'NURS-CATH-URIN',
    '51702',
    'CPT',
    'Urinary catheter insertion',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Insertion of urinary catheter (Foley catheter)',
    20,
    true,
    'nurse',
    true,
    'treatment_room',
    true,
    true,
    '{"catheterType": "urinary"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Nasogastric Tube Insertion',
    'NURS-NG-TUBE',
    '43752',
    'CPT',
    'Nasogastric tube insertion',
    'nursing',
    'routine',
    'general',
    'ANY',
    'Insertion of nasogastric tube for feeding or gastric decompression',
    25,
    true,
    'nurse',
    true,
    'treatment_room',
    true,
    true,
    '{"tubeType": "nasogastric"}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- THERAPY SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Physiotherapy Session - Initial',
    'THER-PHYSIO-INIT',
    '97161',
    'CPT',
    'Initial physiotherapy evaluation and treatment',
    'therapy',
    'new_patient',
    'general',
    'ANY',
    'Initial physiotherapy assessment and first treatment session',
    60,
    true,
    'therapist',
    true,
    'treatment_room',
    true,
    true,
    '{"therapyType": "physiotherapy"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Physiotherapy Session - Follow-up',
    'THER-PHYSIO-FU',
    '97110',
    'CPT',
    'Follow-up physiotherapy treatment session',
    'therapy',
    'follow_up',
    'general',
    'ANY',
    'Therapeutic exercises and manual therapy session',
    45,
    true,
    'therapist',
    true,
    'treatment_room',
    true,
    true,
    '{"therapyType": "physiotherapy"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Occupational Therapy Session',
    'THER-OT',
    '97165',
    'CPT',
    'Occupational therapy session',
    'therapy',
    'routine',
    'general',
    'ANY',
    'Occupational therapy for activities of daily living training',
    45,
    true,
    'therapist',
    true,
    'treatment_room',
    true,
    true,
    '{"therapyType": "occupational_therapy"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Speech Therapy Session',
    'THER-SPEECH',
    '92507',
    'CPT',
    'Speech therapy session',
    'therapy',
    'routine',
    'general',
    'ANY',
    'Speech and language therapy session',
    45,
    true,
    'therapist',
    true,
    'treatment_room',
    true,
    true,
    '{"therapyType": "speech_therapy"}'::jsonb,
    NOW(),
    NOW()
  ),

  -- =========================================================================
  -- ADMINISTRATIVE SERVICES
  -- =========================================================================
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Medical Certificate',
    'ADMIN-MED-CERT',
    'ADMIN-001',
    'LOCAL',
    'Medical certificate issuance',
    'administrative',
    'routine',
    'general',
    'ANY',
    'Issuance of medical certificate for sick leave or fitness purposes',
    10,
    true,
    'physician',
    false,
    NULL,
    true,
    true,
    '{"documentType": "medical_certificate"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Medical Report',
    'ADMIN-MED-REPORT',
    'ADMIN-002',
    'LOCAL',
    'Comprehensive medical report',
    'administrative',
    'routine',
    'general',
    'ANY',
    'Detailed medical report for insurance, legal, or referral purposes',
    30,
    true,
    'physician',
    false,
    NULL,
    true,
    true,
    '{"documentType": "medical_report"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Prescription Copy',
    'ADMIN-PRESC-COPY',
    'ADMIN-003',
    'LOCAL',
    'Prescription copy issuance',
    'administrative',
    'routine',
    'general',
    'ANY',
    'Duplicate copy of prescription for patient records',
    5,
    true,
    'administrative',
    false,
    NULL,
    true,
    true,
    '{"documentType": "prescription_copy"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'Medical Records Copy',
    'ADMIN-MR-COPY',
    'ADMIN-004',
    'LOCAL',
    'Medical records photocopy',
    'administrative',
    'routine',
    'general',
    'ANY',
    'Photocopying of medical records per page',
    NULL,
    true,
    'administrative',
    false,
    NULL,
    true,
    true,
    '{"documentType": "medical_records", "chargePerPage": true}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    '11111111-1111-1111-1111-111111111111',
    'No Objection Certificate (NOC)',
    'ADMIN-NOC',
    'ADMIN-005',
    'LOCAL',
    'No objection certificate issuance',
    'administrative',
    'routine',
    'general',
    'ANY',
    'NOC for visa, insurance, or legal purposes',
    15,
    true,
    'physician',
    false,
    NULL,
    true,
    true,
    '{"documentType": "noc"}'::jsonb,
    NOW(),
    NOW()
  );

-- Verification query
SELECT
  service_category,
  COUNT(*) as service_count
FROM administrative_services
GROUP BY service_category
ORDER BY service_category;

SELECT
  service_name,
  service_code,
  service_category,
  care_setting
FROM administrative_services
ORDER BY service_category, service_name
LIMIT 20;
