-- Medication Master Reference Data
-- This file seeds the medication_master table with common medications

-- Set tenant context (NULL for global medications)
SET app.current_tenant_id = NULL;

-- Common Medications (Global)
INSERT INTO medication_master (
    id,
    tenant_id,
    medication_name,
    generic_name,
    ndc_code,
    atc_code,
    local_code,
    dosage_form,
    strength,
    strength_unit,
    route_of_administration,
    manufacturer,
    controlled_substance_schedule,
    requires_prescription,
    is_active,
    created_at,
    updated_at
) VALUES 
-- Pain Management
(
    'med-pain-001-uuid',
    NULL,
    'Paracetamol',
    'Acetaminophen',
    '12345-678-90',
    'N02BE01',
    'PARA-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-pain-002-uuid',
    NULL,
    'Ibuprofen',
    'Ibuprofen',
    '23456-789-01',
    'M01AE01',
    'IBU-400',
    'tablet',
    '400',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-pain-003-uuid',
    NULL,
    'Morphine',
    'Morphine Sulfate',
    '34567-890-12',
    'N02AA01',
    'MORPH-10',
    'injection',
    '10',
    'mg/ml',
    'intravenous',
    'Controlled Meds UAE',
    'II',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Antibiotics
(
    'med-antibiotic-001-uuid',
    NULL,
    'Amoxicillin',
    'Amoxicillin',
    '45678-901-23',
    'J01CA04',
    'AMOX-500',
    'capsule',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-antibiotic-002-uuid',
    NULL,
    'Ciprofloxacin',
    'Ciprofloxacin',
    '56789-012-34',
    'J01MA02',
    'CIPRO-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Cardiovascular
(
    'med-cardio-001-uuid',
    NULL,
    'Amlodipine',
    'Amlodipine Besylate',
    '67890-123-45',
    'C08CA01',
    'AML-5',
    'tablet',
    '5',
    'mg',
    'oral',
    'Cardio Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-cardio-002-uuid',
    NULL,
    'Metoprolol',
    'Metoprolol Tartrate',
    '78901-234-56',
    'C07AB02',
    'METO-50',
    'tablet',
    '50',
    'mg',
    'oral',
    'Cardio Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Diabetes
(
    'med-diabetes-001-uuid',
    NULL,
    'Metformin',
    'Metformin HCl',
    '89012-345-67',
    'A10BA02',
    'MET-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Diabetes Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-diabetes-002-uuid',
    NULL,
    'Insulin Glargine',
    'Insulin Glargine',
    '90123-456-78',
    'A10AE04',
    'INSULIN-GLAR',
    'injection',
    '100',
    'units/ml',
    'subcutaneous',
    'Diabetes Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Respiratory
(
    'med-resp-001-uuid',
    NULL,
    'Salbutamol',
    'Salbutamol Sulfate',
    '01234-567-89',
    'R03AC02',
    'SALB-100',
    'inhaler',
    '100',
    'mcg/dose',
    'inhalation',
    'Respiratory Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-resp-002-uuid',
    NULL,
    'Prednisolone',
    'Prednisolone',
    '12345-678-90',
    'H02AB06',
    'PRED-5',
    'tablet',
    '5',
    'mg',
    'oral',
    'Respiratory Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Gastrointestinal
(
    'med-gastro-001-uuid',
    NULL,
    'Omeprazole',
    'Omeprazole',
    '23456-789-01',
    'A02BC01',
    'OME-20',
    'capsule',
    '20',
    'mg',
    'oral',
    'Gastro Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    'med-gastro-002-uuid',
    NULL,
    'Loperamide',
    'Loperamide HCl',
    '34567-890-12',
    'A07DA03',
    'LOP-2',
    'capsule',
    '2',
    'mg',
    'oral',
    'Gastro Care UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
);

-- Reset tenant context
SET app.current_tenant_id = NULL;
