-- Procedure Master Reference Data
-- This file seeds the procedure_master table with common medical procedures

-- Set tenant context (NULL for global procedures)
SET app.current_tenant_id = NULL;

-- Common Medical Procedures (Global)
INSERT INTO procedure_master (
    id,
    tenant_id,
    procedure_name,
    cpt_code,
    icd10_pcs_code,
    local_code,
    procedure_category,
    body_system,
    procedure_type,
    anesthesia_type,
    facility_required,
    estimated_duration_minutes,
    preparation_instructions,
    post_procedure_instructions,
    risks_and_complications,
    contraindications,
    consent_required,
    consent_type,
    pre_procedure_requirements,
    post_procedure_monitoring,
    recovery_time_hours,
    is_active,
    created_at,
    updated_at
) VALUES 
-- Minor Surgical Procedures
(
    'proc-minor-001-uuid',
    NULL,
    'Skin Biopsy',
    '11300',
    '0HB00XZ',
    'SKIN-BIOPSY',
    'surgical',
    'integumentary',
    'minor',
    'local',
    'clinic',
    30,
    'Clean area, mark lesion',
    'Keep dressing dry for 24 hours, watch for signs of infection',
    'Bleeding, infection, scarring',
    'Active infection at site, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work if indicated',
    'Monitor for bleeding, infection',
    0.5,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-minor-002-uuid',
    NULL,
    'Excision of Lipoma',
    '11400',
    '0HB60XZ',
    'LIPOMA-EXC',
    'surgical',
    'integumentary',
    'minor',
    'local',
    'clinic',
    45,
    'Mark lesion, clean area',
    'Keep dressing dry, avoid heavy lifting',
    'Bleeding, infection, nerve damage',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work if indicated',
    'Monitor for bleeding, infection',
    1,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-minor-003-uuid',
    NULL,
    'Ingrown Toenail Removal',
    '11750',
    '0HBC0ZZ',
    'TOENAIL-REM',
    'surgical',
    'musculoskeletal',
    'minor',
    'local',
    'clinic',
    20,
    'Clean foot, trim nail',
    'Keep foot elevated, change dressing daily',
    'Bleeding, infection, recurrence',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'None',
    'Monitor for bleeding, infection',
    0.5,
    TRUE,
    NOW(),
    NOW()
),

-- Endoscopic Procedures
(
    'proc-endo-001-uuid',
    NULL,
    'Upper Endoscopy (EGD)',
    '43235',
    '0DB58ZZ',
    'EGD',
    'diagnostic',
    'gastrointestinal',
    'endoscopic',
    'conscious_sedation',
    'hospital',
    30,
    'NPO 8 hours, stop blood thinners',
    'NPO until gag reflex returns, avoid driving',
    'Bleeding, perforation, aspiration',
    'Recent MI, severe respiratory disease',
    TRUE,
    'informed_consent',
    'Blood work, EKG if indicated',
    'Monitor vital signs, gag reflex',
    2,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-endo-002-uuid',
    NULL,
    'Colonoscopy',
    '45378',
    '0DB58ZZ',
    'COLONOSCOPY',
    'diagnostic',
    'gastrointestinal',
    'endoscopic',
    'conscious_sedation',
    'hospital',
    60,
    'Clear liquid diet, bowel prep',
    'Resume normal diet, avoid driving',
    'Bleeding, perforation, infection',
    'Recent MI, severe respiratory disease',
    TRUE,
    'informed_consent',
    'Blood work, EKG if indicated',
    'Monitor vital signs, bleeding',
    4,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-endo-003-uuid',
    NULL,
    'Bronchoscopy',
    '31622',
    '0BB58ZZ',
    'BRONCHOSCOPY',
    'diagnostic',
    'respiratory',
    'endoscopic',
    'general',
    'hospital',
    45,
    'NPO 8 hours, stop blood thinners',
    'NPO until gag reflex returns',
    'Bleeding, pneumothorax, infection',
    'Recent MI, severe respiratory disease',
    TRUE,
    'informed_consent',
    'Blood work, EKG, CXR',
    'Monitor vital signs, respiratory status',
    3,
    TRUE,
    NOW(),
    NOW()
),

-- Cardiovascular Procedures
(
    'proc-cardio-001-uuid',
    NULL,
    'Echocardiogram',
    '93307',
    'B206ZZZ',
    'ECHO',
    'diagnostic',
    'cardiovascular',
    'non_invasive',
    'none',
    'clinic',
    45,
    'No preparation required',
    'No restrictions',
    'None',
    'None',
    FALSE,
    NULL,
    'None',
    'None',
    0,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-cardio-002-uuid',
    NULL,
    'Stress Test (Exercise)',
    '93015',
    '4A02X4Z',
    'STRESS-TEST',
    'diagnostic',
    'cardiovascular',
    'non_invasive',
    'none',
    'hospital',
    60,
    'NPO 4 hours, stop beta-blockers',
    'Resume normal activities',
    'Arrhythmia, MI, cardiac arrest',
    'Recent MI, unstable angina',
    TRUE,
    'informed_consent',
    'EKG, blood work',
    'Monitor EKG, vital signs',
    1,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-cardio-003-uuid',
    NULL,
    'Cardiac Catheterization',
    '93458',
    '02703ZZ',
    'CATH',
    'diagnostic',
    'cardiovascular',
    'invasive',
    'local',
    'hospital',
    90,
    'NPO 8 hours, stop blood thinners',
    'Bed rest 6 hours, avoid heavy lifting',
    'Bleeding, hematoma, MI, stroke',
    'Active bleeding, contrast allergy',
    TRUE,
    'informed_consent',
    'Blood work, EKG, CXR',
    'Monitor vital signs, bleeding',
    6,
    TRUE,
    NOW(),
    NOW()
),

-- Orthopedic Procedures
(
    'proc-ortho-001-uuid',
    NULL,
    'Arthrocentesis (Joint Aspiration)',
    '20610',
    '0SR90ZZ',
    'ARTHROCENTESIS',
    'diagnostic',
    'musculoskeletal',
    'minor',
    'local',
    'clinic',
    20,
    'Clean area, mark joint',
    'Keep dressing dry, avoid heavy use',
    'Bleeding, infection, joint damage',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'None',
    'Monitor for bleeding, infection',
    1,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-ortho-002-uuid',
    NULL,
    'Carpal Tunnel Release',
    '64721',
    '0N5B0ZZ',
    'CTR',
    'surgical',
    'musculoskeletal',
    'minor',
    'local',
    'hospital',
    60,
    'Clean hand, mark incision site',
    'Keep dressing dry, hand therapy',
    'Bleeding, infection, nerve damage',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work if indicated',
    'Monitor for bleeding, infection',
    2,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-ortho-003-uuid',
    NULL,
    'Knee Arthroscopy',
    '29881',
    '0SJC0ZZ',
    'KNEE-ARTHRO',
    'surgical',
    'musculoskeletal',
    'major',
    'general',
    'hospital',
    120,
    'NPO 8 hours, clean knee',
    'Ice, elevation, physical therapy',
    'Bleeding, infection, DVT, nerve damage',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work, EKG',
    'Monitor vital signs, bleeding',
    24,
    TRUE,
    NOW(),
    NOW()
),

-- Gynecological Procedures
(
    'proc-gyn-001-uuid',
    NULL,
    'Pap Smear',
    '88175',
    '0U5B7ZZ',
    'PAP-SMEAR',
    'diagnostic',
    'reproductive',
    'minor',
    'none',
    'clinic',
    10,
    'No preparation required',
    'No restrictions',
    'Bleeding, infection',
    'Active infection',
    FALSE,
    NULL,
    'None',
    'None',
    0,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-gyn-002-uuid',
    NULL,
    'Colposcopy',
    '57452',
    '0U5B7ZZ',
    'COLPOSCOPY',
    'diagnostic',
    'reproductive',
    'minor',
    'none',
    'clinic',
    20,
    'No preparation required',
    'No restrictions, avoid intercourse 24 hours',
    'Bleeding, infection',
    'Active infection',
    TRUE,
    'informed_consent',
    'None',
    'Monitor for bleeding',
    0.5,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-gyn-003-uuid',
    NULL,
    'Dilation and Curettage (D&C)',
    '58120',
    '0U5B7ZZ',
    'D-C',
    'surgical',
    'reproductive',
    'minor',
    'general',
    'hospital',
    45,
    'NPO 8 hours',
    'No heavy lifting, avoid intercourse',
    'Bleeding, infection, perforation',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work, EKG',
    'Monitor vital signs, bleeding',
    4,
    TRUE,
    NOW(),
    NOW()
),

-- Urological Procedures
(
    'proc-urology-001-uuid',
    NULL,
    'Cystoscopy',
    '52000',
    '0TB58ZZ',
    'CYSTOSCOPY',
    'diagnostic',
    'genitourinary',
    'endoscopic',
    'local',
    'hospital',
    30,
    'Empty bladder',
    'Drink plenty of fluids, monitor for bleeding',
    'Bleeding, infection, urinary retention',
    'Active UTI, bleeding disorders',
    TRUE,
    'informed_consent',
    'Urine culture if indicated',
    'Monitor for bleeding, infection',
    2,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-urology-002-uuid',
    NULL,
    'Prostate Biopsy',
    '55700',
    '0VB58ZZ',
    'PROSTATE-BIOPSY',
    'diagnostic',
    'genitourinary',
    'minor',
    'local',
    'hospital',
    45,
    'Antibiotics, enema',
    'Antibiotics, monitor for bleeding',
    'Bleeding, infection, urinary retention',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work, PSA',
    'Monitor for bleeding, infection',
    4,
    TRUE,
    NOW(),
    NOW()
),

-- Ophthalmological Procedures
(
    'proc-ophth-001-uuid',
    NULL,
    'Cataract Surgery',
    '66984',
    '0DSS0ZZ',
    'CATARACT-SURG',
    'surgical',
    'nervous',
    'major',
    'local',
    'hospital',
    90,
    'NPO 8 hours, eye drops',
    'Eye drops, avoid rubbing, follow-up',
    'Bleeding, infection, retinal detachment',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Blood work, eye exam',
    'Monitor for bleeding, infection',
    24,
    TRUE,
    NOW(),
    NOW()
),
(
    'proc-ophth-002-uuid',
    NULL,
    'Laser Retinal Surgery',
    '67028',
    '0DSS0ZZ',
    'LASER-RETINA',
    'surgical',
    'nervous',
    'minor',
    'local',
    'hospital',
    60,
    'Eye drops, dilate pupil',
    'Eye drops, avoid rubbing, follow-up',
    'Bleeding, infection, vision changes',
    'Active infection, bleeding disorders',
    TRUE,
    'informed_consent',
    'Eye exam, OCT',
    'Monitor for bleeding, infection',
    4,
    TRUE,
    NOW(),
    NOW()
);

-- Reset tenant context
SET app.current_tenant_id = NULL;
