-- Oncology-related Lab Test Master Backfill
-- Idempotently upserts oncology-focused lab masters so they can be applied
-- to an existing local DB without rerunning the destructive base lab seed.

INSERT INTO lab_test_master (
  id,
  tenant_id,
  test_name,
  loinc_code,
  cpt_code,
  local_code,
  test_category,
  test_subcategory,
  specimen_type,
  collection_method,
  fasting_required,
  fasting_duration_hours,
  preparation_instructions,
  normal_range_male,
  normal_range_female,
  normal_range_pediatric,
  units,
  methodology,
  turnaround_time_hours,
  report_style,
  lab_discipline,
  reference_lab,
  is_active,
  created_at,
  updated_at
) VALUES
(
  'b1111111-1111-1111-1111-111111111130',
  NULL,
  'Carcinoembryonic Antigen (CEA)',
  '83085-1',
  '82378',
  'LAB-020',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required. Serial monitoring should be done on the same assay platform when possible.',
  'Non-smoker: <3.0, Smoker: <5.0',
  'Non-smoker: <3.0, Smoker: <5.0',
  'Not established',
  'ng/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111131',
  NULL,
  'Cancer Antigen 125 (CA-125)',
  '83082-8',
  '86304',
  'LAB-021',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required.',
  '<35',
  '<35',
  'Not established',
  'U/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111132',
  NULL,
  'Cancer Antigen 19-9 (CA 19-9)',
  '83084-4',
  '86301',
  'LAB-022',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required.',
  '<37',
  '<37',
  'Not established',
  'U/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111133',
  NULL,
  'Alpha-Fetoprotein (AFP)',
  '83073-7',
  '82105',
  'LAB-023',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required.',
  '<10',
  '<10',
  'Not established',
  'ng/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111134',
  NULL,
  'Prostate Specific Antigen (PSA), Total',
  '83112-3',
  '84153',
  'LAB-024',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'Avoid ejaculation, cycling, and prostate manipulation for 24-48 hours before collection when feasible.',
  '<4.0',
  'Not typically applicable',
  'Not established',
  'ng/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111135',
  NULL,
  'Beta-hCG, Quantitative',
  '21198-7',
  '84702',
  'LAB-025',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required.',
  '<5',
  '<5',
  'Age- and context-dependent',
  'IU/L',
  'Immunoassay',
  12,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111136',
  NULL,
  'Lactate Dehydrogenase (LDH)',
  '14804-9',
  '83615',
  'LAB-026',
  'Oncology',
  'Treatment Monitoring',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'Avoid hemolyzed specimens. No fasting required.',
  '140-280',
  '140-280',
  'Age-dependent ranges',
  'U/L',
  'Enzymatic assay',
  4,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  'b1111111-1111-1111-1111-111111111137',
  NULL,
  'Cancer Antigen 15-3 (CA 15-3)',
  '6875-9',
  '86300',
  'LAB-027',
  'Oncology',
  'Tumor Marker',
  'Serum',
  'Venipuncture',
  false,
  NULL,
  'No special preparation required. Serial monitoring should be done on the same assay platform when possible.',
  'Not typically applicable',
  '<30',
  'Not established',
  'U/mL',
  'Immunoassay',
  24,
  'structured',
  'oncology',
  NULL,
  true,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE
SET
  test_name = EXCLUDED.test_name,
  loinc_code = EXCLUDED.loinc_code,
  cpt_code = EXCLUDED.cpt_code,
  local_code = EXCLUDED.local_code,
  test_category = EXCLUDED.test_category,
  test_subcategory = EXCLUDED.test_subcategory,
  specimen_type = EXCLUDED.specimen_type,
  collection_method = EXCLUDED.collection_method,
  fasting_required = EXCLUDED.fasting_required,
  fasting_duration_hours = EXCLUDED.fasting_duration_hours,
  preparation_instructions = EXCLUDED.preparation_instructions,
  normal_range_male = EXCLUDED.normal_range_male,
  normal_range_female = EXCLUDED.normal_range_female,
  normal_range_pediatric = EXCLUDED.normal_range_pediatric,
  units = EXCLUDED.units,
  methodology = EXCLUDED.methodology,
  turnaround_time_hours = EXCLUDED.turnaround_time_hours,
  report_style = EXCLUDED.report_style,
  lab_discipline = EXCLUDED.lab_discipline,
  reference_lab = EXCLUDED.reference_lab,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
