-- Medication Master Seed Data
-- Global medications (tenant_id = NULL) - available to all tenants

INSERT INTO medication_master (
  id,
  tenant_id,
  medication_name,
  generic_name,
  brand_name,
  ndc_code,
  atc_code,
  local_code,
  dosage_form,
  strength,
  route,
  manufacturer,
  drug_class,
  therapeutic_class,
  controlled_substance,
  controlled_class,
  requires_prescription,
  default_frequency,
  default_duration,
  contraindications,
  common_side_effects,
  drug_interactions,
  storage_requirements,
  is_active,
  created_at,
  updated_at
) VALUES
-- Cardiovascular Medications
(
  'a1111111-1111-1111-1111-111111111111',
  NULL,
  'Lisinopril',
  'Lisinopril',
  'Zestril',
  '0378-1050-77',
  'C09AA03',
  'MED-001',
  'tablet',
  '10mg',
  'oral',
  'Mylan Pharmaceuticals',
  'ACE Inhibitor',
  'Cardiovascular',
  false,
  NULL,
  true,
  'Once daily',
  'Ongoing',
  ARRAY['Angioedema', 'Pregnancy', 'Bilateral renal artery stenosis'],
  ARRAY['Cough', 'Dizziness', 'Headache', 'Fatigue'],
  ARRAY['NSAIDs', 'Potassium supplements', 'Lithium'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111112',
  NULL,
  'Atorvastatin',
  'Atorvastatin Calcium',
  'Lipitor',
  '0071-0155-23',
  'C10AA05',
  'MED-002',
  'tablet',
  '20mg',
  'oral',
  'Pfizer',
  'Statin',
  'Cardiovascular',
  false,
  NULL,
  true,
  'Once daily at bedtime',
  'Ongoing',
  ARRAY['Active liver disease', 'Pregnancy', 'Breastfeeding'],
  ARRAY['Muscle pain', 'Headache', 'Nausea', 'Fatigue'],
  ARRAY['Grapefruit juice', 'Cyclosporine', 'Fibrates'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111113',
  NULL,
  'Metoprolol Succinate',
  'Metoprolol Succinate',
  'Toprol-XL',
  '0186-1092-05',
  'C07AB02',
  'MED-003',
  'tablet',
  '50mg',
  'oral',
  'AstraZeneca',
  'Beta Blocker',
  'Cardiovascular',
  false,
  NULL,
  true,
  'Once daily',
  'Ongoing',
  ARRAY['Severe bradycardia', 'Cardiogenic shock', 'Severe asthma'],
  ARRAY['Fatigue', 'Dizziness', 'Cold extremities', 'Bradycardia'],
  ARRAY['Calcium channel blockers', 'Digoxin', 'Clonidine'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),

-- Diabetes Medications
(
  'a1111111-1111-1111-1111-111111111114',
  NULL,
  'Metformin HCl',
  'Metformin Hydrochloride',
  'Glucophage',
  '0087-6070-01',
  'A10BA02',
  'MED-004',
  'tablet',
  '500mg',
  'oral',
  'Bristol-Myers Squibb',
  'Biguanide',
  'Antidiabetic',
  false,
  NULL,
  true,
  'Twice daily with meals',
  'Ongoing',
  ARRAY['Renal impairment', 'Metabolic acidosis', 'Severe hepatic disease'],
  ARRAY['Nausea', 'Diarrhea', 'Abdominal pain', 'Metallic taste'],
  ARRAY['Alcohol', 'Contrast media', 'Cimetidine'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),

-- Antibiotics
(
  'a1111111-1111-1111-1111-111111111115',
  NULL,
  'Amoxicillin',
  'Amoxicillin',
  'Amoxil',
  '0029-6008-22',
  'J01CA04',
  'MED-005',
  'capsule',
  '500mg',
  'oral',
  'GlaxoSmithKline',
  'Penicillin',
  'Antimicrobial',
  false,
  NULL,
  true,
  'Three times daily',
  '7-10 days',
  ARRAY['Penicillin allergy', 'History of cholestatic jaundice'],
  ARRAY['Diarrhea', 'Nausea', 'Skin rash', 'Vomiting'],
  ARRAY['Oral contraceptives', 'Warfarin', 'Methotrexate'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111116',
  NULL,
  'Azithromycin',
  'Azithromycin',
  'Zithromax',
  '0069-3050-30',
  'J01FA10',
  'MED-006',
  'tablet',
  '250mg',
  'oral',
  'Pfizer',
  'Macrolide',
  'Antimicrobial',
  false,
  NULL,
  true,
  'Once daily',
  '5 days',
  ARRAY['Macrolide allergy', 'Severe hepatic impairment'],
  ARRAY['Diarrhea', 'Nausea', 'Abdominal pain', 'Headache'],
  ARRAY['Warfarin', 'Digoxin', 'Ergotamine'],
  'Store at room temperature 15-30°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111117',
  NULL,
  'Ciprofloxacin',
  'Ciprofloxacin HCl',
  'Cipro',
  '0093-0147-01',
  'J01MA02',
  'MED-007',
  'tablet',
  '500mg',
  'oral',
  'Bayer',
  'Fluoroquinolone',
  'Antimicrobial',
  false,
  NULL,
  true,
  'Twice daily',
  '7-14 days',
  ARRAY['Tendon disorders', 'Myasthenia gravis', 'Children under 18'],
  ARRAY['Nausea', 'Diarrhea', 'Dizziness', 'Photosensitivity'],
  ARRAY['Warfarin', 'Theophylline', 'Calcium supplements'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),

-- Pain Management
(
  'a1111111-1111-1111-1111-111111111118',
  NULL,
  'Ibuprofen',
  'Ibuprofen',
  'Advil',
  '0573-0157-70',
  'M01AE01',
  'MED-008',
  'tablet',
  '400mg',
  'oral',
  'Pfizer Consumer Healthcare',
  'NSAID',
  'Analgesic/Anti-inflammatory',
  false,
  NULL,
  false,
  'Three times daily with food',
  '7-10 days',
  ARRAY['Active GI bleeding', 'Severe renal impairment', 'Third trimester pregnancy'],
  ARRAY['Stomach upset', 'Heartburn', 'Dizziness', 'Headache'],
  ARRAY['Aspirin', 'Warfarin', 'ACE inhibitors', 'Lithium'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111119',
  NULL,
  'Paracetamol',
  'Acetaminophen',
  'Tylenol',
  '0045-0265-60',
  'N02BE01',
  'MED-009',
  'tablet',
  '500mg',
  'oral',
  'Johnson & Johnson',
  'Analgesic',
  'Analgesic/Antipyretic',
  false,
  NULL,
  false,
  'Every 4-6 hours as needed',
  'As needed (max 5 days)',
  ARRAY['Severe hepatic impairment', 'Alcohol abuse'],
  ARRAY['Rare: skin rash', 'Hepatotoxicity with overdose'],
  ARRAY['Warfarin', 'Alcohol', 'Isoniazid'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),
(
  'a1111111-1111-1111-1111-111111111120',
  NULL,
  'Tramadol HCl',
  'Tramadol Hydrochloride',
  'Ultram',
  '0045-0537-60',
  'N02AX02',
  'MED-010',
  'tablet',
  '50mg',
  'oral',
  'Janssen Pharmaceuticals',
  'Opioid Analgesic',
  'Analgesic',
  true,
  'Schedule IV',
  true,
  'Every 4-6 hours as needed',
  '5-7 days',
  ARRAY['Respiratory depression', 'Acute intoxication', 'MAO inhibitor use'],
  ARRAY['Nausea', 'Dizziness', 'Constipation', 'Drowsiness'],
  ARRAY['SSRIs', 'MAO inhibitors', 'Warfarin', 'Carbamazepine'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),

-- Respiratory Medications
(
  'a1111111-1111-1111-1111-111111111121',
  NULL,
  'Salbutamol',
  'Albuterol Sulfate',
  'Ventolin',
  '0173-0682-20',
  'R03AC02',
  'MED-011',
  'inhaler',
  '100mcg/actuation',
  'inhalation',
  'GlaxoSmithKline',
  'Beta-2 Agonist',
  'Bronchodilator',
  false,
  NULL,
  true,
  '2 puffs every 4-6 hours as needed',
  'As needed',
  ARRAY['Hypersensitivity to albuterol'],
  ARRAY['Tremor', 'Nervousness', 'Headache', 'Palpitations'],
  ARRAY['Beta blockers', 'Diuretics', 'Digoxin'],
  'Store at room temperature 20-25°C. Protect from freezing',
  true,
  NOW(),
  NOW()
),

-- Gastrointestinal Medications
(
  'a1111111-1111-1111-1111-111111111122',
  NULL,
  'Omeprazole',
  'Omeprazole',
  'Prilosec',
  '0186-1099-31',
  'A02BC01',
  'MED-012',
  'capsule',
  '20mg',
  'oral',
  'AstraZeneca',
  'Proton Pump Inhibitor',
  'Gastrointestinal',
  false,
  NULL,
  true,
  'Once daily before breakfast',
  '14-28 days',
  ARRAY['Hypersensitivity to PPIs'],
  ARRAY['Headache', 'Abdominal pain', 'Nausea', 'Diarrhea'],
  ARRAY['Clopidogrel', 'Warfarin', 'Diazepam', 'Phenytoin'],
  'Store at room temperature 20-25°C in dry place',
  true,
  NOW(),
  NOW()
),

-- Antihistamines
(
  'a1111111-1111-1111-1111-111111111123',
  NULL,
  'Cetirizine HCl',
  'Cetirizine Hydrochloride',
  'Zyrtec',
  '0045-0847-06',
  'R06AE07',
  'MED-013',
  'tablet',
  '10mg',
  'oral',
  'UCB Pharma',
  'Antihistamine',
  'Allergic Conditions',
  false,
  NULL,
  false,
  'Once daily',
  'As needed',
  ARRAY['Severe renal impairment', 'End-stage renal disease'],
  ARRAY['Drowsiness', 'Fatigue', 'Dry mouth', 'Headache'],
  ARRAY['CNS depressants', 'Theophylline'],
  'Store at room temperature 20-25°C',
  true,
  NOW(),
  NOW()
),

-- Antihypertensives
(
  'a1111111-1111-1111-1111-111111111124',
  NULL,
  'Amlodipine Besylate',
  'Amlodipine Besylate',
  'Norvasc',
  '0069-1530-68',
  'C08CA01',
  'MED-014',
  'tablet',
  '5mg',
  'oral',
  'Pfizer',
  'Calcium Channel Blocker',
  'Cardiovascular',
  false,
  NULL,
  true,
  'Once daily',
  'Ongoing',
  ARRAY['Severe hypotension', 'Cardiogenic shock', 'Severe aortic stenosis'],
  ARRAY['Ankle edema', 'Flushing', 'Palpitations', 'Dizziness'],
  ARRAY['Simvastatin', 'CYP3A4 inhibitors'],
  'Store at room temperature 15-30°C',
  true,
  NOW(),
  NOW()
),

-- Anticoagulants
(
  'a1111111-1111-1111-1111-111111111125',
  NULL,
  'Warfarin Sodium',
  'Warfarin Sodium',
  'Coumadin',
  '0056-0170-70',
  'B01AA03',
  'MED-015',
  'tablet',
  '5mg',
  'oral',
  'Bristol-Myers Squibb',
  'Anticoagulant',
  'Cardiovascular',
  false,
  NULL,
  true,
  'Once daily at same time',
  'Ongoing with monitoring',
  ARRAY['Active bleeding', 'Pregnancy', 'Severe hypertension'],
  ARRAY['Bleeding', 'Bruising', 'Anemia', 'Alopecia'],
  ARRAY['NSAIDs', 'Aspirin', 'Antibiotics', 'Vitamin K'],
  'Store at room temperature 15-30°C. Protect from light',
  true,
  NOW(),
  NOW()
);
