-- Medication Master Reference Data
-- This file seeds the medication_master table with common medications

-- Set tenant context (NULL for global medications)
SET app.current_tenant_id = NULL;

-- Common Medications (Global)
INSERT INTO medication_master (
    id,
    tenant_id,
    medication_name,
    generic_name,
    ndc_code,
    atc_code,
    local_code,
    dosage_form,
    strength,
    strength_unit,
    route_of_administration,
    manufacturer,
    controlled_substance_schedule,
    requires_prescription,
    is_active,
    created_at,
    updated_at
) VALUES 
-- Pain Management
(
    uuid_from_text('med-pain-001-uuid'),
    NULL,
    'Paracetamol',
    'Acetaminophen',
    uuid_from_text('12345-678-90'),
    'N02BE01',
    'PARA-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-pain-002-uuid'),
    NULL,
    'Ibuprofen',
    'Ibuprofen',
    uuid_from_text('23456-789-01'),
    'M01AE01',
    'IBU-400',
    'tablet',
    '400',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-pain-003-uuid'),
    NULL,
    'Morphine',
    'Morphine Sulfate',
    uuid_from_text('34567-890-12'),
    'N02AA01',
    'MORPH-10',
    'injection',
    '10',
    'mg/ml',
    'intravenous',
    'Controlled Meds UAE',
    'II',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Antibiotics
(
    uuid_from_text('med-antibiotic-001-uuid'),
    NULL,
    'Amoxicillin',
    'Amoxicillin',
    uuid_from_text('45678-901-23'),
    'J01CA04',
    'AMOX-500',
    'capsule',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-antibiotic-002-uuid'),
    NULL,
    'Ciprofloxacin',
    'Ciprofloxacin',
    uuid_from_text('56789-012-34'),
    'J01MA02',
    'CIPRO-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Generic Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Cardiovascular
(
    uuid_from_text('med-cardio-001-uuid'),
    NULL,
    'Amlodipine',
    'Amlodipine Besylate',
    uuid_from_text('67890-123-45'),
    'C08CA01',
    'AML-5',
    'tablet',
    '5',
    'mg',
    'oral',
    'Cardio Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-cardio-002-uuid'),
    NULL,
    'Metoprolol',
    'Metoprolol Tartrate',
    uuid_from_text('78901-234-56'),
    'C07AB02',
    'METO-50',
    'tablet',
    '50',
    'mg',
    'oral',
    'Cardio Pharma UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Diabetes
(
    uuid_from_text('med-diabetes-001-uuid'),
    NULL,
    'Metformin',
    'Metformin HCl',
    uuid_from_text('89012-345-67'),
    'A10BA02',
    'MET-500',
    'tablet',
    '500',
    'mg',
    'oral',
    'Diabetes Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-diabetes-002-uuid'),
    NULL,
    'Insulin Glargine',
    'Insulin Glargine',
    uuid_from_text('90123-456-78'),
    'A10AE04',
    'INSULIN-GLAR',
    'injection',
    '100',
    'units/ml',
    'subcutaneous',
    'Diabetes Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Respiratory
(
    uuid_from_text('med-resp-001-uuid'),
    NULL,
    'Salbutamol',
    'Salbutamol Sulfate',
    uuid_from_text('01234-567-89'),
    'R03AC02',
    'SALB-100',
    'inhaler',
    '100',
    'mcg/dose',
    'inhalation',
    'Respiratory Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-resp-002-uuid'),
    NULL,
    'Prednisolone',
    'Prednisolone',
    uuid_from_text('12345-678-90'),
    'H02AB06',
    'PRED-5',
    'tablet',
    '5',
    'mg',
    'oral',
    'Respiratory Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Gastrointestinal
(
    uuid_from_text('med-gastro-001-uuid'),
    NULL,
    'Omeprazole',
    'Omeprazole',
    uuid_from_text('23456-789-01'),
    'A02BC01',
    'OME-20',
    'capsule',
    '20',
    'mg',
    'oral',
    'Gastro Care UAE',
    NULL,
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('med-gastro-002-uuid'),
    NULL,
    'Loperamide',
    'Loperamide HCl',
    uuid_from_text('34567-890-12'),
    'A07DA03',
    'LOP-2',
    'capsule',
    '2',
    'mg',
    'oral',
    'Gastro Care UAE',
    NULL,
    FALSE,
    TRUE,
    NOW(),
    NOW()
);

-- Reset tenant context
SET app.current_tenant_id = NULL;
