-- Imaging Study Master Seed Data
-- Global imaging studies (tenant_id = NULL) - available to all tenants

INSERT INTO imaging_study_master (
  id,
  tenant_id,
  study_name,
  cpt_code,
  local_code,
  modality,
  body_part,
  study_category,
  contrast_required,
  contrast_type,
  preparation_instructions,
  positioning_instructions,
  contraindications,
  radiation_dose,
  estimated_duration_minutes,
  facility_requirements,
  equipment_requirements,
  radiologist_required,
  is_active,
  created_at,
  updated_at
) VALUES
-- X-Ray Studies
(
  'c1111111-1111-1111-1111-111111111111',
  NULL,
  'Chest X-Ray, 2 Views',
  '71046',
  'IMG-001',
  'X-ray',
  'Chest',
  'Diagnostic',
  false,
  NULL,
  'Remove all jewelry and metal objects from chest area. Wear gown if needed.',
  'PA and lateral views. Patient stands against plate.',
  ARRAY['Pregnancy (unless essential)'],
  '0.1 mSv',
  15,
  'Clinic or Hospital',
  'Digital X-ray system',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111112',
  NULL,
  'Chest X-Ray, Single View',
  '71045',
  'IMG-002',
  'X-ray',
  'Chest',
  'Diagnostic',
  false,
  NULL,
  'Remove all jewelry and metal objects. Gown may be required.',
  'AP or PA view. Patient standing or supine.',
  ARRAY['Pregnancy (unless essential)'],
  '0.05 mSv',
  10,
  'Clinic or Hospital',
  'Digital X-ray system',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111113',
  NULL,
  'Abdominal X-Ray (KUB)',
  '74018',
  'IMG-003',
  'X-ray',
  'Abdomen',
  'Diagnostic',
  false,
  NULL,
  'No special preparation. Inform if pregnant.',
  'Supine AP view of abdomen.',
  ARRAY['Pregnancy (unless essential)'],
  '0.7 mSv',
  15,
  'Clinic or Hospital',
  'Digital X-ray system',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111114',
  NULL,
  'Hand X-Ray',
  '73130',
  'IMG-004',
  'X-ray',
  'Hand',
  'Diagnostic',
  false,
  NULL,
  'Remove rings, bracelets, and watch.',
  'PA, oblique, and lateral views of affected hand.',
  ARRAY['None specific'],
  '0.001 mSv',
  15,
  'Clinic or Hospital',
  'Digital X-ray system or portable',
  true,
  true,
  NOW(),
  NOW()
),

-- CT Scans
(
  'c1111111-1111-1111-1111-111111111115',
  NULL,
  'CT Head without Contrast',
  '70450',
  'IMG-005',
  'CT',
  'Head',
  'Diagnostic',
  false,
  NULL,
  'Remove all metal objects from head/neck area. No fasting required.',
  'Patient supine, head in head holder.',
  ARRAY['Pregnancy (unless essential)'],
  '2 mSv',
  20,
  'Hospital or Imaging Center',
  'CT scanner',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111116',
  NULL,
  'CT Head with Contrast',
  '70460',
  'IMG-006',
  'CT',
  'Head',
  'Diagnostic',
  true,
  'IV',
  'NPO 4 hours before. Adequate kidney function required (check creatinine).',
  'Patient supine, IV access established.',
  ARRAY['Pregnancy', 'Severe renal impairment', 'Contrast allergy', 'Metformin use'],
  '2 mSv',
  30,
  'Hospital or Imaging Center',
  'CT scanner with contrast injector',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111117',
  NULL,
  'CT Abdomen and Pelvis with Contrast',
  '74177',
  'IMG-007',
  'CT',
  'Abdomen/Pelvis',
  'Diagnostic',
  true,
  'IV and Oral',
  'NPO 4 hours. Drink oral contrast 2 hours and 30 min before. Check kidney function.',
  'Patient supine. IV contrast administered during scan.',
  ARRAY['Pregnancy', 'Severe renal impairment (eGFR <30)', 'Severe contrast allergy'],
  '10 mSv',
  45,
  'Hospital or Imaging Center',
  'CT scanner with contrast injector',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111118',
  NULL,
  'CT Chest without Contrast',
  '71250',
  'IMG-008',
  'CT',
  'Chest',
  'Diagnostic',
  false,
  NULL,
  'Remove metal objects from chest. No fasting required.',
  'Patient supine, arms above head.',
  ARRAY['Pregnancy (unless essential)'],
  '7 mSv',
  25,
  'Hospital or Imaging Center',
  'CT scanner',
  true,
  true,
  NOW(),
  NOW()
),

-- MRI Studies
(
  'c1111111-1111-1111-1111-111111111119',
  NULL,
  'MRI Brain without Contrast',
  '70551',
  'IMG-009',
  'MRI',
  'Brain',
  'Diagnostic',
  false,
  NULL,
  'Remove all metal objects. Inform of any implants, pacemakers, or metal in body.',
  'Patient supine in MRI scanner. Head coil used.',
  ARRAY['Pacemaker', 'Cochlear implants', 'Some metal implants', 'Severe claustrophobia'],
  'No radiation',
  45,
  'Hospital or Imaging Center',
  '1.5T or 3T MRI scanner',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111120',
  NULL,
  'MRI Brain with and without Contrast',
  '70553',
  'IMG-010',
  'MRI',
  'Brain',
  'Diagnostic',
  true,
  'IV (Gadolinium)',
  'NPO 4 hours. Remove all metal. Check kidney function (eGFR). Inform of allergies.',
  'Patient supine. IV established. Scans before and after contrast.',
  ARRAY['Pacemaker', 'Severe renal impairment (eGFR <30)', 'Gadolinium allergy'],
  'No radiation',
  60,
  'Hospital or Imaging Center',
  '1.5T or 3T MRI scanner with injector',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111121',
  NULL,
  'MRI Lumbar Spine without Contrast',
  '72148',
  'IMG-011',
  'MRI',
  'Lumbar Spine',
  'Diagnostic',
  false,
  NULL,
  'Remove all metal objects. Inform of any spinal hardware or implants.',
  'Patient supine. Spine coil used.',
  ARRAY['Pacemaker', 'Some spinal implants', 'Severe claustrophobia'],
  'No radiation',
  40,
  'Hospital or Imaging Center',
  '1.5T or 3T MRI scanner',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111122',
  NULL,
  'MRI Knee without Contrast',
  '73721',
  'IMG-012',
  'MRI',
  'Knee',
  'Diagnostic',
  false,
  NULL,
  'Remove metal objects from leg. Inform of any knee hardware.',
  'Patient supine or prone. Knee in dedicated coil.',
  ARRAY['Metal hardware in knee (relative)', 'Severe claustrophobia'],
  'No radiation',
  35,
  'Hospital or Imaging Center',
  'MRI scanner with extremity coil',
  true,
  true,
  NOW(),
  NOW()
),

-- Ultrasound Studies
(
  'c1111111-1111-1111-1111-111111111123',
  NULL,
  'Ultrasound Abdomen Complete',
  '76700',
  'IMG-013',
  'Ultrasound',
  'Abdomen',
  'Diagnostic',
  false,
  NULL,
  'NPO 6-8 hours before exam. May drink water.',
  'Patient supine or lateral decubitus. Full bladder may be needed.',
  ARRAY['None'],
  'No radiation',
  30,
  'Clinic or Hospital',
  'Ultrasound machine with abdominal probe',
  false,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111124',
  NULL,
  'Ultrasound Pelvis (Transabdominal)',
  '76856',
  'IMG-014',
  'Ultrasound',
  'Pelvis',
  'Diagnostic',
  false,
  NULL,
  'Drink 32 oz water 1 hour before. Do not empty bladder.',
  'Patient supine. Full bladder required for optimal imaging.',
  ARRAY['None'],
  'No radiation',
  30,
  'Clinic or Hospital',
  'Ultrasound machine with pelvic probe',
  false,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111125',
  NULL,
  'Ultrasound Thyroid',
  '76536',
  'IMG-015',
  'Ultrasound',
  'Thyroid',
  'Diagnostic',
  false,
  NULL,
  'No special preparation. Wear loose collar.',
  'Patient supine with neck extended. Small pillow under shoulders.',
  ARRAY['None'],
  'No radiation',
  20,
  'Clinic or Hospital',
  'Ultrasound machine with high-frequency probe',
  false,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111126',
  NULL,
  'Carotid Doppler Ultrasound',
  '93880',
  'IMG-016',
  'Ultrasound',
  'Carotid Arteries',
  'Diagnostic',
  false,
  NULL,
  'No special preparation. Wear loose collar.',
  'Patient supine with neck slightly extended and turned.',
  ARRAY['None'],
  'No radiation',
  45,
  'Clinic or Hospital',
  'Ultrasound with Doppler capability',
  false,
  true,
  NOW(),
  NOW()
),

-- Mammography
(
  'c1111111-1111-1111-1111-111111111127',
  NULL,
  'Mammogram, Screening, Bilateral',
  '77067',
  'IMG-017',
  'X-ray',
  'Breast',
  'Screening',
  false,
  NULL,
  'No deodorant, powder, or lotion on breast/underarm area. Schedule after menstrual period.',
  'Standing. Breast compressed between plates for CC and MLO views.',
  ARRAY['Pregnancy', 'Recent breast surgery (relative)'],
  '0.4 mSv',
  30,
  'Imaging Center or Hospital',
  'Digital mammography unit',
  true,
  true,
  NOW(),
  NOW()
),
(
  'c1111111-1111-1111-1111-111111111128',
  NULL,
  'Mammogram, Diagnostic, Bilateral',
  '77066',
  'IMG-018',
  'X-ray',
  'Breast',
  'Diagnostic',
  false,
  NULL,
  'No deodorant, powder, or lotion. Bring prior mammograms if available.',
  'Standing. Additional views as needed based on findings.',
  ARRAY['Pregnancy'],
  '0.4-0.8 mSv',
  45,
  'Imaging Center or Hospital',
  'Digital mammography unit',
  true,
  true,
  NOW(),
  NOW()
);
