-- Imaging Study Master Reference Data
-- This file seeds the imaging_study_master table with common imaging studies

-- Set tenant context (NULL for global imaging studies)
SET app.current_tenant_id = NULL;

-- Common Imaging Studies (Global)
INSERT INTO imaging_study_master (
    id,
    tenant_id,
    study_name,
    cpt_code,
    local_code,
    modality,
    body_part,
    study_category,
    contrast_required,
    contrast_type,
    preparation_instructions,
    positioning_instructions,
    contraindications,
    radiation_dose,
    estimated_duration_minutes,
    facility_requirements,
    equipment_requirements,
    radiologist_required,
    is_active,
    created_at,
    updated_at
) VALUES 
-- X-Ray Studies
(
    uuid_from_text('img-xray-001-uuid'),
    NULL,
    'Chest X-Ray (PA & Lateral)',
    '71020',
    'CXR-PA-LAT',
    'X-ray',
    'chest',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all jewelry and metal objects from chest area',
    'PA: Standing, arms at sides, chin up. Lateral: Left side against cassette',
    'Pregnancy (relative contraindication)',
    '0.1 mSv',
    15,
    'clinic',
    'X-ray machine, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-xray-002-uuid'),
    NULL,
    'Abdominal X-Ray (KUB)',
    '74000',
    'AXR-KUB',
    'X-ray',
    'abdomen',
    'diagnostic',
    FALSE,
    NULL,
    'No preparation required',
    'Supine position, arms at sides',
    'Pregnancy (relative contraindication)',
    '0.7 mSv',
    10,
    'clinic',
    'X-ray machine, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-xray-003-uuid'),
    NULL,
    'Lumbar Spine X-Ray (AP & Lateral)',
    '72100',
    'LS-XRAY-AP-LAT',
    'X-ray',
    'lumbar_spine',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all jewelry and metal objects',
    'AP: Supine. Lateral: Left lateral decubitus',
    'Pregnancy (relative contraindication)',
    '1.5 mSv',
    20,
    'clinic',
    'X-ray machine, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- CT Studies
(
    uuid_from_text('img-ct-001-uuid'),
    NULL,
    'CT Chest without Contrast',
    '71260',
    'CT-CHEST-NC',
    'CT',
    'chest',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all jewelry and metal objects',
    'Supine, arms above head',
    'Pregnancy (absolute contraindication)',
    '7 mSv',
    15,
    'hospital',
    'CT scanner, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-ct-002-uuid'),
    NULL,
    'CT Chest with Contrast',
    '71260',
    'CT-CHEST-C',
    'CT',
    'chest',
    'diagnostic',
    TRUE,
    'IV',
    'NPO 4 hours, remove all jewelry and metal objects',
    'Supine, arms above head',
    'Pregnancy, contrast allergy, renal insufficiency',
    '7 mSv',
    20,
    'hospital',
    'CT scanner, contrast injector, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-ct-003-uuid'),
    NULL,
    'CT Abdomen and Pelvis with Contrast',
    '74177',
    'CT-ABD-PEL-C',
    'CT',
    'abdomen_pelvis',
    'diagnostic',
    TRUE,
    'IV',
    'NPO 4 hours, drink oral contrast 1 hour prior',
    'Supine, arms above head',
    'Pregnancy, contrast allergy, renal insufficiency',
    '10 mSv',
    25,
    'hospital',
    'CT scanner, contrast injector, lead aprons',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-ct-004-uuid'),
    NULL,
    'CT Head without Contrast',
    '70450',
    'CT-HEAD-NC',
    'CT',
    'head',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all jewelry and metal objects',
    'Supine, head in head holder',
    'Pregnancy (absolute contraindication)',
    '2 mSv',
    10,
    'hospital',
    'CT scanner, head holder',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- MRI Studies
(
    uuid_from_text('img-mri-001-uuid'),
    NULL,
    'MRI Brain without Contrast',
    '70551',
    'MRI-BRAIN-NC',
    'MRI',
    'brain',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all metal objects, jewelry, hearing aids',
    'Supine, head in head coil',
    'Pacemaker, metal implants, claustrophobia',
    '0 mSv',
    45,
    'hospital',
    'MRI scanner, head coil',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-mri-002-uuid'),
    NULL,
    'MRI Lumbar Spine without Contrast',
    '72141',
    'MRI-LS-NC',
    'MRI',
    'lumbar_spine',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all metal objects, jewelry',
    'Supine, spine coil',
    'Pacemaker, metal implants, claustrophobia',
    '0 mSv',
    60,
    'hospital',
    'MRI scanner, spine coil',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-mri-003-uuid'),
    NULL,
    'MRI Knee without Contrast',
    '73721',
    'MRI-KNEE-NC',
    'MRI',
    'knee',
    'diagnostic',
    FALSE,
    NULL,
    'Remove all metal objects, jewelry',
    'Supine, knee coil',
    'Pacemaker, metal implants, claustrophobia',
    '0 mSv',
    45,
    'hospital',
    'MRI scanner, knee coil',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Ultrasound Studies
(
    uuid_from_text('img-us-001-uuid'),
    NULL,
    'Abdominal Ultrasound',
    '76700',
    'US-ABD',
    'Ultrasound',
    'abdomen',
    'diagnostic',
    FALSE,
    NULL,
    'NPO 8 hours for gallbladder, full bladder for pelvis',
    'Supine, gel applied to abdomen',
    'None',
    '0 mSv',
    30,
    'clinic',
    'Ultrasound machine, gel',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-us-002-uuid'),
    NULL,
    'Pelvic Ultrasound',
    '76856',
    'US-PELVIC',
    'Ultrasound',
    'pelvis',
    'diagnostic',
    FALSE,
    NULL,
    'Full bladder required',
    'Supine, gel applied to lower abdomen',
    'None',
    '0 mSv',
    25,
    'clinic',
    'Ultrasound machine, gel',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-us-003-uuid'),
    NULL,
    'Carotid Doppler',
    '93880',
    'US-CAROTID',
    'Ultrasound',
    'carotid_arteries',
    'diagnostic',
    FALSE,
    NULL,
    'No preparation required',
    'Supine, head turned, gel applied to neck',
    'None',
    '0 mSv',
    30,
    'clinic',
    'Ultrasound machine with Doppler, gel',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Mammography
(
    uuid_from_text('img-mammo-001-uuid'),
    NULL,
    'Screening Mammography (Bilateral)',
    '77067',
    'MAMMO-SCREEN',
    'Mammography',
    'breast',
    'screening',
    FALSE,
    NULL,
    'No deodorant, powder, or lotion on breasts',
    'Compression views: CC and MLO',
    'Pregnancy (relative contraindication)',
    '0.4 mSv',
    20,
    'clinic',
    'Mammography machine, compression paddles',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-mammo-002-uuid'),
    NULL,
    'Diagnostic Mammography (Bilateral)',
    '77065',
    'MAMMO-DIAG',
    'Mammography',
    'breast',
    'diagnostic',
    FALSE,
    NULL,
    'No deodorant, powder, or lotion on breasts',
    'Additional compression and magnification views',
    'Pregnancy (relative contraindication)',
    '0.6 mSv',
    30,
    'clinic',
    'Mammography machine, compression paddles',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),

-- Nuclear Medicine
(
    uuid_from_text('img-nuc-001-uuid'),
    NULL,
    'Bone Scan (Whole Body)',
    '78315',
    'BONE-SCAN-WB',
    'Nuclear Medicine',
    'skeleton',
    'diagnostic',
    TRUE,
    'IV',
    'No preparation required',
    'Supine, whole body imaging',
    'Pregnancy, breastfeeding',
    '4.2 mSv',
    180,
    'hospital',
    'Gamma camera, radiopharmaceutical',
    TRUE,
    TRUE,
    NOW(),
    NOW()
),
(
    uuid_from_text('img-nuc-002-uuid'),
    NULL,
    'Thyroid Scan',
    '78012',
    'THYROID-SCAN',
    'Nuclear Medicine',
    'thyroid',
    'diagnostic',
    TRUE,
    'oral',
    'NPO 4 hours, stop thyroid medications',
    'Supine, neck extended',
    'Pregnancy, breastfeeding',
    '0.1 mSv',
    60,
    'hospital',
    'Gamma camera, radiopharmaceutical',
    TRUE,
    TRUE,
    NOW(),
    NOW()
);

-- Reset tenant context
SET app.current_tenant_id = NULL;
