-- Procedure Master Seed Data
-- Global procedures (tenant_id = NULL) - available to all tenants

INSERT INTO procedure_master (
  id,
  tenant_id,
  procedure_name,
  cpt_code,
  icd10_pcs_code,
  local_code,
  procedure_category,
  body_system,
  procedure_type,
  anesthesia_type,
  facility_required,
  estimated_duration_minutes,
  preparation_instructions,
  post_procedure_instructions,
  risks_and_complications,
  contraindications,
  consent_required,
  consent_type,
  pre_procedure_requirements,
  post_procedure_monitoring,
  recovery_time_hours,
  is_active,
  created_at,
  updated_at
) VALUES
-- Minor Office Procedures
(
  'd1111111-1111-1111-1111-111111111111',
  NULL,
  'Excision of Skin Lesion, Simple',
  '11400',
  NULL,
  'PROC-001',
  'Surgical',
  'Integumentary',
  'Minor',
  'Local',
  'Clinic',
  30,
  'Clean area thoroughly. No specific fasting required.',
  'Keep area clean and dry. Change dressing daily. Watch for signs of infection.',
  ARRAY['Infection', 'Bleeding', 'Scarring', 'Recurrence', 'Allergic reaction to anesthetic'],
  ARRAY['Active skin infection at site', 'Bleeding disorder', 'Allergy to local anesthetic'],
  true,
  'Informed Consent',
  ARRAY['Recent medication list', 'Allergy history', 'Bleeding disorder screening'],
  'Monitor for bleeding and signs of infection. Pain management.',
  24,
  true,
  NOW(),
  NOW()
),
(
  'd1111111-1111-1111-1111-111111111112',
  NULL,
  'Incision and Drainage of Abscess',
  '10060',
  NULL,
  'PROC-002',
  'Surgical',
  'Integumentary',
  'Minor',
  'Local',
  'Clinic',
  20,
  'Clean affected area. May require antibiotic course before procedure.',
  'Keep wound packed. Change dressing as instructed. Complete antibiotic course.',
  ARRAY['Infection spread', 'Bleeding', 'Scarring', 'Recurrence'],
  ARRAY['Necrotizing fasciitis', 'Severe cellulitis requiring IV antibiotics'],
  true,
  'Informed Consent',
  ARRAY['Blood sugar control if diabetic', 'Recent vital signs'],
  'Monitor temperature, wound drainage, and pain level.',
  12,
  true,
  NOW(),
  NOW()
),
(
  'd1111111-1111-1111-1111-111111111113',
  NULL,
  'Joint Injection (Knee)',
  '20610',
  NULL,
  'PROC-003',
  'Therapeutic',
  'Musculoskeletal',
  'Minor',
  'Local',
  'Clinic',
  15,
  'Discontinue blood thinners if safe to do so (per physician). Clean knee area.',
  'Rest joint for 24-48 hours. Ice application. Avoid strenuous activity for 2 days.',
  ARRAY['Infection', 'Bleeding into joint', 'Allergic reaction', 'Tendon rupture (rare)'],
  ARRAY['Active joint infection', 'Skin infection over injection site', 'Bleeding disorder'],
  true,
  'Informed Consent',
  ARRAY['X-ray or imaging within 6 months', 'Current medications', 'Allergy history'],
  'Monitor for increased pain, swelling, warmth, or fever.',
  2,
  true,
  NOW(),
  NOW()
),

-- Gastrointestinal Procedures
(
  'd1111111-1111-1111-1111-111111111114',
  NULL,
  'Colonoscopy with Biopsy',
  '45380',
  '0DJD8ZZ',
  'PROC-004',
  'Diagnostic',
  'Gastrointestinal',
  'Endoscopic',
  'Moderate Sedation',
  'Hospital',
  60,
  'Clear liquid diet 24 hours prior. Bowel prep as prescribed. NPO 8 hours before.',
  'Rest for remainder of day. No driving for 24 hours. Resume normal diet gradually.',
  ARRAY['Bleeding', 'Perforation', 'Adverse reaction to sedation', 'Infection'],
  ARRAY['Severe diverticulitis', 'Toxic megacolon', 'Recent MI', 'Pregnancy'],
  true,
  'Informed Consent + Sedation Consent',
  ARRAY['Recent labs (CBC, coagulation)', 'Bowel prep completion', 'Driver arranged', 'NPO status confirmed'],
  'Monitor vital signs every 15 min until awake. Check for abdominal pain or bleeding.',
  4,
  true,
  NOW(),
  NOW()
),
(
  'd1111111-1111-1111-1111-111111111115',
  NULL,
  'Upper Endoscopy (EGD) with Biopsy',
  '43239',
  '0DJ08ZZ',
  'PROC-005',
  'Diagnostic',
  'Gastrointestinal',
  'Endoscopic',
  'Moderate Sedation',
  'Hospital',
  45,
  'NPO after midnight (minimum 8 hours). Stop blood thinners if instructed.',
  'NPO for 2 hours. Throat may be numb - no hot liquids. Rest for remainder of day.',
  ARRAY['Aspiration', 'Bleeding', 'Perforation', 'Adverse reaction to sedation'],
  ARRAY['Recent MI', 'Severe respiratory disease', 'Inability to tolerate sedation'],
  true,
  'Informed Consent + Sedation Consent',
  ARRAY['Recent labs if indicated', 'NPO status confirmed', 'Driver arranged', 'Medication review'],
  'Monitor airway and vital signs. Watch for bleeding, chest pain, or difficulty swallowing.',
  4,
  true,
  NOW(),
  NOW()
),

-- Cardiovascular Procedures
(
  'd1111111-1111-1111-1111-111111111116',
  NULL,
  'Cardiac Catheterization, Diagnostic',
  '93458',
  '4A023N7',
  'PROC-006',
  'Diagnostic',
  'Cardiovascular',
  'Invasive',
  'Local + Moderate Sedation',
  'Hospital',
  90,
  'NPO 6-8 hours. Hydrate well day before. Hold metformin 48 hours before.',
  'Bed rest 4-6 hours. Pressure on groin. Monitor access site. Resume medications.',
  ARRAY['Bleeding', 'Hematoma', 'Arrhythmia', 'Stroke', 'MI', 'Kidney injury', 'Death (rare)'],
  ARRAY['Active bleeding', 'Severe renal failure', 'Severe contrast allergy (relative)'],
  true,
  'Informed Consent + Anesthesia Consent',
  ARRAY['Recent ECG', 'Labs: CBC, BMP, PT/INR, troponin', 'CXR', 'NPO status', 'IV access', 'Consent signed'],
  'Continuous cardiac monitoring. Vital signs q15min x4, then q30min x2. Groin checks. Pedal pulses.',
  12,
  true,
  NOW(),
  NOW()
),

-- Obstetric/Gynecologic Procedures
(
  'd1111111-1111-1111-1111-111111111117',
  NULL,
  'Dilation and Curettage (D&C)',
  '58120',
  '0UDB7ZZ',
  'PROC-007',
  'Surgical',
  'Reproductive',
  'Minor',
  'General or Regional',
  'Hospital',
  30,
  'NPO after midnight. Arrange driver. Discontinue aspirin/NSAIDs if instructed.',
  'Rest for 24-48 hours. No tampons, intercourse, or douching for 2 weeks. Light bleeding normal.',
  ARRAY['Uterine perforation', 'Infection', 'Hemorrhage', 'Asherman syndrome', 'Anesthesia complications'],
  ARRAY['Active pelvic infection', 'Desired pregnancy', 'Coagulopathy (relative)'],
  true,
  'Informed Consent + Anesthesia Consent',
  ARRAY['Pregnancy test', 'CBC', 'Type and screen', 'NPO status', 'IV access'],
  'Monitor vital signs and vaginal bleeding. Pain management. Post-op teaching.',
  6,
  true,
  NOW(),
  NOW()
),

-- Orthopedic Procedures
(
  'd1111111-1111-1111-1111-111111111118',
  NULL,
  'Arthroscopy, Knee, Surgical',
  '29881',
  '0SJD4ZZ',
  'PROC-008',
  'Surgical',
  'Musculoskeletal',
  'Major',
  'General or Regional',
  'Surgery Center',
  90,
  'NPO after midnight. Pre-op antibiotics. Arrange ride home.',
  'Ice, elevation, crutches as needed. Physical therapy. No weight bearing as directed.',
  ARRAY['Infection', 'DVT/PE', 'Nerve/vessel injury', 'Stiffness', 'Persistent pain'],
  ARRAY['Active knee infection', 'Severe medical comorbidities', 'DVT in affected leg'],
  true,
  'Informed Consent + Anesthesia Consent',
  ARRAY['Recent MRI', 'Pre-op labs', 'ECG if indicated', 'Medical clearance', 'Physical exam'],
  'Neurovascular checks. Pain management. Ice and elevation. Monitor for DVT signs.',
  24,
  true,
  NOW(),
  NOW()
),

-- Respiratory Procedures
(
  'd1111111-1111-1111-1111-111111111119',
  NULL,
  'Bronchoscopy with Bronchoalveolar Lavage',
  '31624',
  '0B9B8ZZ',
  'PROC-009',
  'Diagnostic',
  'Respiratory',
  'Endoscopic',
  'Moderate Sedation',
  'Hospital',
  45,
  'NPO 6-8 hours. Continue respiratory medications. Chest X-ray within 24 hours.',
  'NPO 2 hours. Rest. May have sore throat. No driving 24 hours. Watch for fever.',
  ARRAY['Bleeding', 'Pneumothorax', 'Hypoxemia', 'Bronchospasm', 'Infection'],
  ARRAY['Severe hypoxemia', 'Recent MI', 'Severe bleeding disorder', 'Unstable cardiac status'],
  true,
  'Informed Consent + Sedation Consent',
  ARRAY['Recent CXR', 'ABG or SpO2', 'PT/INR if on anticoagulants', 'ECG', 'Consent signed'],
  'Continuous pulse oximetry. Vital signs. Post-procedure CXR if indicated. NPO until gag reflex returns.',
  4,
  true,
  NOW(),
  NOW()
),

-- Urological Procedures
(
  'd1111111-1111-1111-1111-111111111120',
  NULL,
  'Cystoscopy, Diagnostic',
  '52000',
  '0TJB8ZZ',
  'PROC-010',
  'Diagnostic',
  'Urinary',
  'Endoscopic',
  'Local or Moderate Sedation',
  'Clinic or Hospital',
  20,
  'May take prophylactic antibiotic. Empty bladder before procedure.',
  'Drink plenty of fluids. Burning with urination is normal for 24-48 hours.',
  ARRAY['UTI', 'Urethral trauma', 'Bleeding', 'Urinary retention'],
  ARRAY['Active UTI', 'Acute prostatitis', 'Urethral stricture (severe)'],
  true,
  'Informed Consent',
  ARRAY['Recent urinalysis', 'Urine culture if indicated', 'Allergy history'],
  'Monitor for urinary retention. First void after procedure. Watch for hematuria.',
  2,
  true,
  NOW(),
  NOW()
),

-- Ophthalmic Procedures
(
  'd1111111-1111-1111-1111-111111111121',
  NULL,
  'Cataract Extraction with IOL Implant',
  '66984',
  '08RJ3JZ',
  'PROC-011',
  'Surgical',
  'Eye',
  'Minor',
  'Topical + Sedation',
  'Surgery Center',
  30,
  'Use prescribed eye drops. Arrange driver. Light meal morning of surgery.',
  'Use eye drops as prescribed. Wear eye shield at night. No heavy lifting. No water in eye.',
  ARRAY['Infection', 'Retinal detachment', 'Increased eye pressure', 'Bleeding', 'Vision loss'],
  ARRAY['Active eye infection', 'Uncontrolled glaucoma', 'Retinal detachment'],
  true,
  'Informed Consent',
  ARRAY['Recent eye exam', 'IOL calculations', 'Medical clearance', 'Dilated eye exam'],
  'Eye examination. Intraocular pressure check. Pain and vision assessment. Eye shield in place.',
  6,
  true,
  NOW(),
  NOW()
),

-- Dermatologic Procedures
(
  'd1111111-1111-1111-1111-111111111122',
  NULL,
  'Mohs Micrographic Surgery',
  '17311',
  NULL,
  'PROC-012',
  'Surgical',
  'Integumentary',
  'Minor',
  'Local',
  'Clinic',
  180,
  'Continue blood thinners unless instructed otherwise. Eat normal breakfast. Wear comfortable clothes.',
  'Keep wound covered. Elevate if possible. Ice packs for swelling. Pain medication as needed.',
  ARRAY['Bleeding', 'Infection', 'Scarring', 'Nerve damage', 'Recurrence'],
  ARRAY['Active infection at surgical site', 'Allergy to local anesthesia'],
  true,
  'Informed Consent',
  ARRAY['Medication list', 'Allergy history', 'Previous skin cancer history', 'Driver if extensive surgery'],
  'Monitor for bleeding and signs of infection. Wound care instructions. Pain management.',
  24,
  true,
  NOW(),
  NOW()
),

-- Pain Management Procedures
(
  'd1111111-1111-1111-1111-111111111123',
  NULL,
  'Epidural Steroid Injection, Lumbar',
  '62323',
  '3E0S33Z',
  'PROC-013',
  'Therapeutic',
  'Nervous System',
  'Minor',
  'Local + Sedation',
  'Surgery Center',
  45,
  'NPO 4 hours. Continue regular medications. Arrange driver.',
  'Rest for 24 hours. Ice application. Resume activities gradually. Keep injection log.',
  ARRAY['Infection', 'Bleeding', 'Nerve injury', 'Dural puncture', 'Allergic reaction'],
  ARRAY['Active infection', 'Pregnancy', 'Bleeding disorder', 'Allergy to steroids or contrast'],
  true,
  'Informed Consent',
  ARRAY['Recent MRI of lumbar spine', 'PT/INR if on anticoagulants', 'Blood sugar monitoring if diabetic'],
  'Neuro checks. Monitor injection site. Blood pressure monitoring. Pain assessment.',
  4,
  true,
  NOW(),
  NOW()
),

-- ENT Procedures
(
  'd1111111-1111-1111-1111-111111111124',
  NULL,
  'Tonsillectomy',
  '42825',
  '0CTN0ZZ',
  'PROC-014',
  'Surgical',
  'Respiratory',
  'Major',
  'General',
  'Hospital',
  60,
  'NPO after midnight. Pre-op antibiotics. Arrange care at home for 7-10 days.',
  'Soft/cold diet for 2 weeks. Pain medication. No aspirin/ibuprofen x2 weeks. Rest.',
  ARRAY['Hemorrhage (immediate or delayed)', 'Dehydration', 'Infection', 'Anesthesia complications'],
  ARRAY['Active infection', 'Bleeding disorder', 'Recent URI (relative)', 'Anesthesia contraindications'],
  true,
  'Informed Consent + Anesthesia Consent',
  ARRAY['CBC', 'PT/INR', 'Type and screen', 'Recent strep test', 'Medical clearance', 'NPO status'],
  'Monitor for bleeding. Pain control. Ensure adequate PO intake. Watch for dehydration.',
  48,
  true,
  NOW(),
  NOW()
),

-- Dental Procedures
(
  'd1111111-1111-1111-1111-111111111125',
  NULL,
  'Tooth Extraction, Simple',
  '41899',
  NULL,
  'PROC-015',
  'Surgical',
  'Oral',
  'Minor',
  'Local',
  'Clinic',
  30,
  'No special preparation unless sedation planned. Continue medications.',
  'Bite gauze for 30 min. No smoking, straws, or vigorous rinsing x24 hours. Soft diet.',
  ARRAY['Bleeding', 'Infection', 'Dry socket', 'Nerve injury', 'Sinus perforation'],
  ARRAY['Acute infection (relative)', 'Bleeding disorder', 'Recent bisphosphonate use'],
  true,
  'Informed Consent',
  ARRAY['Recent dental X-ray', 'Medical history', 'Medication list', 'Allergy history'],
  'Monitor for excessive bleeding. Pain control. Oral hygiene instructions.',
  24,
  true,
  NOW(),
  NOW()
);
