-- Seed: PRM communication templates

INSERT INTO communication_templates (
  id,
  tenant_id,
  code,
  name,
  description,
  category,
  channel,
  language,
  subject,
  body,
  variables_schema,
  approval_status,
  version,
  content_hash,
  is_active,
  created_at,
  created_by,
  updated_at
) VALUES
  (
    uuid_from_text('prm-template-apt-reminder-sms'),
    '11111111-1111-1111-1111-111111111111',
    'apt-reminder-24h-sms',
    'Appointment Reminder - 24 Hours',
    'SMS reminder sent 24 hours before appointment.',
    'care',
    'sms',
    'en',
    NULL,
    'Hi {{patient_name}}, your appointment with {{provider_name}} is on {{appointment_date}} at {{appointment_time}}.',
    '{"patient_name":"string","provider_name":"string","appointment_date":"string","appointment_time":"string"}'::jsonb,
    'approved',
    1,
    'd5f2f7b1f6e2a02d9e77d2c0f8e5d6c3b1a9f0e4d3c2b1a0f9e8d7c6b5a4f3e2',
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  ),
  (
    uuid_from_text('prm-template-payment-reminder-email'),
    '11111111-1111-1111-1111-111111111111',
    'payment-reminder-email',
    'Payment Reminder',
    'Email reminder for upcoming invoice due date.',
    'billing',
    'email',
    'en',
    'Payment Reminder for Invoice {{invoice_number}}',
    'Dear {{patient_name}}, your invoice {{invoice_number}} of {{amount}} is due on {{due_date}}.',
    '{"patient_name":"string","invoice_number":"string","amount":"string","due_date":"string"}'::jsonb,
    'approved',
    1,
    'a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0011223344556677',
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  ),
  (
    uuid_from_text('prm-template-consent-whatsapp'),
    '11111111-1111-1111-1111-111111111111',
    'consent-request-whatsapp',
    'Consent Request',
    'WhatsApp request to complete consent form.',
    'care',
    'whatsapp',
    'en',
    NULL,
    'Hi {{patient_name}}, please complete your consent form: {{consent_link}}.',
    '{"patient_name":"string","consent_link":"string"}'::jsonb,
    'approved',
    1,
    'f0e1d2c3b4a5968778695a4b3c2d1e0f11223344556677889900aabbccddeeff',
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  )
ON CONFLICT (tenant_id, code, language, channel, version) DO NOTHING;
