-- Seed: PRM engagement rules

INSERT INTO engagement_rules (
  id,
  tenant_id,
  code,
  name,
  description,
  category,
  trigger_event_type,
  trigger_event_subtype,
  condition_expr,
  schedule_mode,
  delay_seconds,
  action_type,
  action_payload,
  priority,
  cooldown_seconds,
  idempotency_window,
  max_executions_per_day,
  is_active,
  created_at,
  created_by,
  updated_at
) VALUES
  (
    uuid_from_text('prm-rule-appointment-reminder'),
    '11111111-1111-1111-1111-111111111111',
    'appointment-reminder-24h-sms',
    '24h Appointment Reminder (SMS)',
    'Send SMS reminder 24 hours before appointment.',
    'appointment_reminders',
    'appointment_confirmed',
    NULL,
    '{"and":[{"field":"event.payload.appointment_date","op":"gte","value":"{{now_plus_24h}}"}]}'::jsonb,
    'DELAYED',
    82800,
    'SEND_MESSAGE',
    '{"channel":"sms","template_code":"apt-reminder-24h-sms","purpose":"care"}'::jsonb,
    100,
    3600,
    86400,
    3,
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  ),
  (
    uuid_from_text('prm-rule-payment-reminder'),
    '11111111-1111-1111-1111-111111111111',
    'payment-reminder-email',
    'Payment Reminder (Email)',
    'Send email reminder 7 days before invoice due date.',
    'billing_followup',
    'invoice_generated',
    NULL,
    '{"and":[{"field":"event.payload.due_date","op":"gte","value":"{{now_plus_7d}}"}]}'::jsonb,
    'DELAYED',
    604800,
    'SEND_MESSAGE',
    '{"channel":"email","template_code":"payment-reminder-email","purpose":"billing"}'::jsonb,
    90,
    7200,
    86400,
    2,
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  ),
  (
    uuid_from_text('prm-rule-consent-request'),
    '11111111-1111-1111-1111-111111111111',
    'consent-request-task',
    'Consent Request Task',
    'Create a staff task to request consent.',
    'care_coordination',
    'encounter_completed',
    NULL,
    '{"and":[{"field":"event.payload.requires_consent","op":"eq","value":true}]}'::jsonb,
    'IMMEDIATE',
    0,
    'CREATE_TASK',
    '{"task_type":"consent_needed","title":"Request patient consent","priority":2,"assign_role":"admin","due_at":"+2d"}'::jsonb,
    80,
    3600,
    43200,
    5,
    true,
    NOW(),
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    NOW()
  )
ON CONFLICT (tenant_id, code) DO NOTHING;
